name: Build

on:
  push:
    branches: 
      - features/**
    paths:
      - src/**
      - tests/**
  pull_request:
    branches: 
      - develop
      - main
    paths:
      - src/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore ./src/AzureMapsControl.Components/AzureMapsControl.Components.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/AzureMapsControl.Components/AzureMapsControl.Components.csproj
    - name: NPM Install
      run: cd ./src/AzureMapsControl.Components && npm i --force
    - name: Lint
      run: cd ./src/AzureMapsControl.Components && npx eslint -c eslint.config.mjs
    - name: Build Typescript
      run: cd ./src/AzureMapsControl.Components && npm run build